### PR TITLE
update cocoaLumberjack to 2.o

### PR DESCRIPTION
**Pull request by zzzworm**

### CODE REVIEW

**Comment by s4nchez** [comment]
Thank you for this PR.

I'm happy with your changes. Just not sure about changing podspec to point to your repo. I see two options:

1. Keep mine and I'll keep integrating future changes.
2. You take over this pod (not sure how to transfer it in cocoapods) and point it to your repo as being the main one.

Thoughts?

**Comment by zzzworm** [comment]
I used podspec point to my repo, because my project use pod point to it.Now, I revert it

**Comment by s4nchez** [comment]
That's fine. I'll merge it then.

**Comment by s4nchez** [comment]
BTW, @zzzworm, would you like me to add you as contributor to this pod? 

That way you can publish this version to the main repo...

**Comment by zzzworm** [comment]
thx your invite. I'd like to be a contributor.

**Comment by s4nchez** [comment]
Done. You can now merge pull requests directly on this repo.

**Pull request merged**
